### ISSUE TITLE
animatie van logo

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/cortexarts.github.io#6]
Er zit een belangrijk en lelijk verschil in de lijndikte van de C en de A bij het uitrollen van het logo. Klopt dat of mankeer ik wat aan mijn ogen, wat werkelijk zo is...;-) Na het uitrollen moet het logo volgens mij weer inrollen

**Comment by jasperdrescher** [comment]
De A lijkt dikker inderdaad. :( En het inrollen kan door een gif te maken die eigenlijk dus het reversed is. En dan laad je hem op dezelfed manier in.

**Comment by Feikovandijk** [comment]
De letters zijn wel even dik, komt vgm gewoon door de vorm van de A. Ik zal de letter iets kleiner maken in de animatie, en een reversed gif maken!

**Comment by jasperdrescher** [comment]
Nice man!
