### ISSUE TITLE
links openen in nieuw tabblad

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/cortexarts.github.io#7]
Alle hrefs moeten in nieuwe tabbladen openen
Hier staat een javascript oplossing voor de hele site: http://html.com/attributes/a-target/
Geen idee waar het geparkeerd moet worden.
Kan het voor iedere href apart doen maar dat kan niet de bedoeling zijn.

**Comment by jasperdrescher** [comment]
Als je voor iedere "a" object een _blank toevoegt waar het nodig is is dat stukken handiger. Daarnaast zijn het ook niet veel links.
