### ISSUE TITLE
portretten toevoegen

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/cortexarts.github.io#8]
In de about pagina zou ik het wel leuk vinden als er beeld in de vakken komt van onze smeoelen. Dat wil zeggen: karikaturen van onzelf?

**Comment by jasperdrescher** [comment]
Ja ik wilde eerst alleen kleuren erin, aangezien ik het niet heel handig vond als er foto's van ons op staan. Maar een soort portret or iets is inderdaad wel een leukere oplossing :)
